# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: |
        wget https://sheff.online/EN-HCNetSDKV6.1.9.48_build20230410_linux64.zip
        unzip EN-HCNetSDKV6.1.9.48_build20230410_linux64.zip
        mv EN-HCNetSDKV6.1.9.48_build20230410_linux64 hiksdk
        ls
        pwd
        echo $LD_LIBRARY_PATH
        echo $CGO_CXXFLAGS
        echo $CGO_LDFLAGS
        go build cmd/hiklib-cli/hiklib-cli.go
      env:
        LD_LIBRARY_PATH: "/home/runner/work/hiklib-cli/hiklib-cli/hiksdk/lib" 
        CGO_CXXFLAGS: "-I/home/runner/work/hiklib-cli/hiklib-cli/hiksdk/incEn/" 
        CGO_LDFLAGS: "-L/home/runner/work/hiklib-cli/hiklib-cli/hiksdk/lib -lhcnetsdk" 
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: hiklib-cli
